title: Methodist Girls' School
url: https://www.mgs.moe.edu.sg
favicon: /images/Common/logo-mgs.png
colors:
  primary-color: "#0a2240"
  secondary-color: "#b18646"
  media-colors:
    - title: media-color-one
      color: "#a39e8e"
    - title: media-color-two
      color: "#6d4857"
    - title: media-color-three
      color: "#304066"
    - title: media-color-four
      color: "#656565"
    - title: media-color-five
      color: "#6f5b34"
description: Methodist Girls’ School (MGS) was founded by Miss Sophia Blackmore
  on 15 August 1887. Supported by the Women’s Foreign Missionary Society of the
  Methodist Episcopal Church in America, Miss Blackmore, an Australian
  missionary, came to Singapore with a mission – to provide girls with an
  education.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.dt6ildc2mnegy.amplifyapp.com
prod: https://master.dt6ildc2mnegy.amplifyapp.com
shareicon: /images/Common/logo-mgs.png
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
resources_name: highlights
google_analytics_ga4: ""
